scope: postgres-cluster
namespace: /db/
name: postgres-1

restapi:
  listen: 0.0.0.0:8008
  connect_address: #{NODE_IP}:8008

etcd:
  hosts: #{ETCD_HOSTS}
  protocol: http
  retry_timeout: 10
  ttl: 30

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5
        synchronous_commit: "remote_apply"
        synchronous_standby_names: 'ANY 1 (postgres-2, postgres-3)'

  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: 0.0.0.0:5432
  connect_address: #{NODE_IP}:5432
  data_dir: /data/patroni
  bin_dir: /usr/lib/postgresql/15/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: #{REPLICATION_PASSWORD}
    superuser:
      username: postgres
      password: #{POSTGRES_PASSWORD}
  parameters:
    unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false